AWSTemplateFormatVersion: "2010-09-09"
Description: Template to create a VPC Stack

Resources:
  VPCStack:                       #just a element name / section name to reffer to. 
    Type: AWS::EC2::VPC
    Properties:
        CidrBlock: 10.0.0.0/16
        EnableDnsSupport: true
        EnableDnsHostnames: true
        Tags:
            - Key: Name
              Value: aws-vpc-with-cft       #actual name of the VPC